/**
 * Skool creator keyword list — sve mora imati Skool signal.
 * Organizovano po kategorijama bola koji kreatori osećaju.
 */

export const CREATOR_KEYWORDS = [

  // ── 1. DIREKTNO VLASNIŠTVO ─────────────────────────────────────────────────
  'my skool community',
  'my skool group',
  'my skool members',
  'I run a skool community',
  'I own a skool community',
  'running my skool',
  'launched my skool',
  'building my skool community',
  'growing my skool',
  'skool community owner',
  'managing my skool',
  'I have a skool community',
  'skool group owner',

  // ── 2. API / ZAPIER / WEBHOOK GREŠKE ──────────────────────────────────────
  'skool zapier error',
  'skool zapier not working',
  'skool zapier stopped working',
  'skool zapier broken',
  'skool webhook failed',
  'skool webhook not triggering',
  'skool catch hook error',
  'skool API key broken',
  'skool API key invalid',
  'skool x-api-secret error',
  'skool API 429',
  'skool API 404',
  'skool API rate limit',
  'skool CLI API',
  'skool invalid session_id',
  'skool API authentication expired',
  'reconnect skool account zapier',
  'skool zapier task limit',
  'skool zapier polling delay',
  'skool zapier instant trigger missing',
  'skool zapier status hold',
  'skool make.com integration',
  'skool make.com not working',
  'skool n8n integration',
  'skool n8n workflow',
  'skool pabbly connect',
  'skool data mapping issue',
  'skool missing email field zapier',
  'skool JSON results array missing',

  // ── 3. KURS / CLASSROOM PROBLEMI ──────────────────────────────────────────
  'skool course not found error',
  'skool unlock course failed',
  'skool private course access error',
  'skool custom course ID',
  'skool classroom mapping problem',
  'skool lesson completion trigger',
  'skool multiple courses unlock',
  'skool drip feed broken',
  'skool drip content not working',
  'skool drip content problem',
  'skool video hosting problem',
  'skool video not loading',
  'skool course builder limited',
  'skool modules not working',
  'skool no certificates',
  'skool quiz feature missing',
  'skool course completion tracking',
  'skool content organization problem',
  'skool hidden modules',
  'skool manual course assignment',

  // ── 4. MEMBERSHIP / PRISTUP GREŠKE ────────────────────────────────────────
  'skool manual approval problem',
  'skool pending members',
  'skool invite link expired',
  'skool bulk invite error',
  'skool CSV import failed',
  'skool duplicate member record',
  'skool member list export',
  'skool user not found',
  'skool wrong email mapping',
  'skool member directory access',
  'skool admin permissions error',
  'skool member management',
  'skool bulk message members',
  'skool DM members',
  'skool direct message limit',
  'skool tagging members problem',

  // ── 5. OTKAZIVANJE / UKLANJANJE (Top pain point) ──────────────────────────
  'skool manual removal member',
  'skool remove cancelled member',
  'skool stripe cancellation sync',
  'skool revoke access automation',
  'skool silent churn',
  'skool failed payment removal',
  'skool subscription end access',
  'skool cancellation workaround',
  'remove member skool webhook',
  'skool thrivecart cancellation',
  'kajabi cancellation skool removal',
  'skool stop billing but stay in group',
  'skool google sheets member removal',

  // ── 6. ONBOARDING AUTOMATIZACIJA ──────────────────────────────────────────
  'skool welcome DM automation',
  'skool personalized welcome message',
  'skool onboarding bottleneck',
  'skool new member sequence',
  'skool intro post reminder',
  'skool onboarding call booking',
  'skool automated waitlist',
  'skool qualify new members',
  'skool membership questions export',
  'skool CRM sync latency',
  'skool onboarding sequence',
  'skool welcome sequence',
  'skool new member onboarding',

  // ── 7. CRM / EMAIL INTEGRACIJA ────────────────────────────────────────────
  'skool gohighlevel integration',
  'skool GHL integration',
  'skool GHL sync problem',
  'skool activecampaign integration',
  'skool convertkit integration',
  'skool kit automation skool',
  'skool mailchimp integration',
  'skool beehiiv integration',
  'skool hubspot sync',
  'skool pipedrive integration',
  'skool email collection',
  'skool collect emails',
  'skool email not working',
  'skool CRM integration',
  'skool automation workflow',
  'skool no automation',
  'doing everything manually skool',

  // ── 8. PLAĆANJE / FUNNEL INTEGRACIJA ──────────────────────────────────────
  'skool stripe integration',
  'skool stripe problem',
  'skool payment processing problem',
  'skool clickfunnels integration',
  'skool thrivecart integration',
  'skool stan store integration',
  'skool systeme.io integration',
  'skool samcart integration',
  'skool order bump',
  'skool upsell automation',
  'skool checkout not converting',
  'skool checkout problem',
  'skool payment failed',
  'skool refund problem',
  'skool free trial to paid',
  'skool free to paid conversion',
  'skool members never upgrade',
  'free members not converting skool',

  // ── 9. OPERATIVNI ALATI ───────────────────────────────────────────────────
  'skool google sheets integration',
  'skool airtable integration',
  'skool slack notifications',
  'skool calendly integration',
  'skool zoom automation',
  'skool calendar feature',
  'skool live event problem',
  'skool events not working',

  // ── 10. GAMIFIKACIJA / ANGAŽOVANJE ────────────────────────────────────────
  'skool points farming',
  'skool leaderboard reset problem',
  'skool level unlock error',
  'skool custom level names',
  'skool level gated content',
  'skool points system manual',
  'skool engagement tracking',
  'skool ghost members',
  'skool inactive members',
  'skool reward automation',
  'skool badge system',
  'skool gamification problem',
  'skool leaderboard issue',
  'skool community ghost town',
  'skool ghost town',
  'nobody posts in my skool',
  'skool members not engaging',
  'skool members not posting',
  'skool members not active',
  'skool community engagement problem',
  'low engagement skool community',
  'skool member retention',
  'skool community churn',
  'members leaving my skool',
  'reactivate skool members',
  'win back skool members',

  // ── 11. COMMUNITY RAST / AKVIZICIJA ──────────────────────────────────────
  'how to get members into skool',
  'skool community not getting members',
  'growing skool from zero',
  'promoting my skool community',
  'skool community not growing',
  'how to grow skool community',
  'how to increase skool engagement',
  'how to retain skool members',
  'how to onboard skool members',
  'how to collect emails on skool',
  'how to automate skool',
  'how to reduce churn skool',
  'struggling with skool community',
  'skool community problems',
  'skool community help',
  'help with skool community',

  // ── 12. FACEBOOK GROUP MIGRACIJA ──────────────────────────────────────────
  'moving from facebook group to skool',
  'facebook group to skool migration',
  'switched facebook group to skool',
  'left facebook group for skool',
  'skool vs facebook groups for community',
  'facebook group members not moving to skool',
  'migrating facebook community to skool',

  // ── 13. PLATFORMA — OGRANIČENJA ───────────────────────────────────────────
  'skool limitations',
  'skool platform limitations',
  'skool missing features',
  'skool feature request',
  'skool no white label',
  'skool custom domain',
  'skool no custom branding',
  'skool funnel limitation',
  'skool landing page problem',
  'skool no drip content',
  'skool content scheduling',
  'skool mobile app problem',
  'skool notification problem',
  'skool moderation tools',
  'skool analytics missing',
  'skool analytics not enough',
  'skool reporting limited',
  'skool member activity tracking',
  'skool search not working',
  'skool admin tools lacking',

  // ── 14. MIGRACIJA / POREĐENJE ─────────────────────────────────────────────
  'switching from kajabi to skool',
  'left kajabi for skool',
  'moved community to skool',
  'migrated to skool',
  'switching from circle to skool',
  'left circle for skool',
  'mighty networks to skool',
  'leaving skool for kajabi',
  'leaving skool for circle',
  'cancelled skool',
  'leaving skool',
  'why I left skool',
  'skool vs kajabi for community',
  'skool vs circle for community',
  'skool vs mighty networks',
  'skool vs discord for community',
  'skool vs slack for community',
  'skool vs facebook groups for community',
  'skool alternative for community',

  // ── 15. FINANSIJE / ROI ────────────────────────────────────────────────────
  'skool not worth it',
  'skool too expensive',
  'skool roi problem',
  'wasting money on skool',
  'skool subscription not worth',
  'cancel skool subscription',
  'is skool worth it for creators',

  // ── 16. DAILY OPERATIONS / COMMUNITY MANAGEMENT ───────────────────────────
  'skool daily prompt automation',
  'skool weekly wins post automation',
  'skool AI moderator',
  'skool spam detection',
  'skool auto reply comments',
  'skool community feed noise',
  'skool pinned posts problem',
  'skool announcement feature',
  'skool overwhelming to manage',
  'skool community moderator issues',

  // ── 17. VERTIKALE ─────────────────────────────────────────────────────────
  'skool for coaches',
  'skool for consultants',
  'skool for fitness coaches',
  'skool for online coaches',
  'skool mastermind community',
  'skool for agency owners',
  'skool for solopreneurs',
  'skool membership site',
  'skool coaching program',
];

// ── Subreddits za targeted listing ───────────────────────────────────────────
export const CREATOR_SUBREDDITS = [
  'entrepreneur', 'EntrepreneurRideAlong', 'AskEntrepreneurs',
  'onlinebusiness', 'smallbusiness',
  'coursecreators', 'onlinecourse', 'elearning',
  'marketing', 'digitalmarketing', 'socialmediamarketing',
  'coaching', 'consulting', 'freelance',
  'sidehustle', 'passive_income',
  'contentcreation', 'youtubers',
  'SaaS', 'nocode', 'zapier',
];

// ── Priority keywords — highest signal, run on every subreddit ───────────────
export const PRIORITY_KEYWORDS = [
  // Core ownership + pain combos
  'my skool community',
  'skool community ghost town',
  'skool members not engaging',
  'skool ghost town',
  // Automation pain
  'skool zapier error',
  'skool zapier not working',
  'skool webhook failed',
  'skool make.com integration',
  'skool n8n integration',
  'skool no automation',
  'doing everything manually skool',
  // Email/CRM
  'skool email collection',
  'skool GHL integration',
  'skool activecampaign integration',
  // Cancellation pain
  'skool remove cancelled member',
  'skool stripe cancellation sync',
  'skool revoke access automation',
  // Churn
  'skool community churn',
  'members leaving my skool',
  'cancelled skool',
  'leaving skool',
  // Platform limits
  'skool limitations',
  'skool drip content problem',
  'skool analytics missing',
  'skool course not found error',
  // Migration
  'switching from kajabi to skool',
  'moving from facebook group to skool',
  'skool vs kajabi for community',
  // Growth
  'skool community not growing',
  'how to grow skool community',
  'struggling with skool community',
  // Finance
  'skool not worth it',
  'skool free to paid conversion',
];
